### PR TITLE
feat(menu): add active style for left menu

### PR DESCRIPTION
**Pull request by ryomahan**
use redux + useLocation(in react-router-dom) + useEffect realize left menu active style.

**This program may not be the best solution, this is just a simple attempt on my part, welcome to discuss.**

 - [x] I hereby declare this contribution to be licenced under the [MIT license](https://opensource.org/licenses/MIT)

### CODE REVIEW

**Comment by atompie** [comment]
@ryomahan I have checked and I would like to merge but I see one error. The highlight disappears on some sub-pages. I guess we need an array of routes that highlight certain menu-row. And I need to make a change to distinguish flows for segmentation and integration.

Screenshot from 2022-11-21 10-00-44

**Comment by ryomahan** [comment]
@atompie This is a point I ignored. My idea is that we can modify the click method of opening the flow(segmentation and integration) page, I think it's easier than defining an array. Let me try it.

**Comment by ryomahan** [comment]
React state management is too complicated for me. Please let me know if I'm wrong.

**Comment by ryomahan** [comment]
And maybe something wrong with project's github workflow, there is no file named Dockerfile in root path.

**Pull request merged**
